New upstream version 5.1.2

diff --git a/sysstat.in b/sysstat.in
--- a/sysstat.in
+++ b/sysstat.in
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/bin/sh
 #
 # Author: Klaus.Franken@fth2.siemens.de
 # Die Okt 12 10:05:41 EDT 1999
@@ -8,15 +8,30 @@
 #	Now use '-d' option when starting sar.
 # 2000/01/22 - Sebastien Godard <sebastien.godard@wanadoo.fr>
 #	Rewritten from scratch. Call sadc instead of sar.
+# 2004/10/10 - Sebastien Godard (sysstat <at> wanadoo.fr)
+#	Now returns real exit code.
 #
-# /etc/rc.d/init.d/sysstat
+# INIT_DIR/sysstat
 #
+
+RETVAL=0
+# Remove flag indicating that sadc was successfully launched
+rm -f /tmp/sysstat.run
 
 # See how we were called.
 case "$1" in
   start)
         echo -n "Calling the system activity data collector (sadc): "
-        PREFIX/lib/sa/sadc -F -L - QUOTE
+        SU SA_LIB_DIR/sadc -F -L - && touch /tmp/sysstat.run QUOTE
+
+# Try to guess if sadc was successfully launched. The difficulty
+# here is that the exit code is lost when the above command is
+# run via "su foo -c ..."
+	if [ ! -f /tmp/sysstat.run ]; then
+		RETVAL=1
+	else
+		rm -f /tmp/sysstat.run
+	fi
         echo
         ;;
   stop|status|restart|reload)
@@ -25,4 +40,5 @@ case "$1" in
         echo "Usage: sysstat {start|stop|status|restart|reload}"
         exit 1
 esac
+exit ${RETVAL}
 
